#!/usr/bin/env bash
#
#   boardconfig - an fff script to update the FLM's board config section
#
#   Copyright (C) 2012 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# exit codes
# 0: ok
# 1: no corresponding boardconfig found
# 2: ubc did not finish its operation

# build the response header first
echo "HTTP/1.1 200 OK"
echo "Content-Type: text/plain"
echo "Transfer-Encoding: chunked"
echo ""

# ... followed by the response body
HOME=$PWD/cgi-bin
TOOLS=$HOME/tools

NOBUF="$HOME/stdbuf -i0 -o0 -e0"

HOST=192.168.255.1
BATCH=$(echo "$QUERY_STRING" | sed -n 's/^.*batch=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")
SERIAL=$(echo "$QUERY_STRING" | sed -n 's/^.*serial=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")

# check if boardconfig file exists and is writeable
FN=$(printf "$BATCH/$BATCH%06d" $SERIAL)

[ -w $TOOLS/$FN ] \
	&& { echo 2 > $HOME/code; } \
	|| { echo 1 > $HOME/code; exit 1; }

env PWDS=$TOOLS $NOBUF $TOOLS/ubc -b $BATCH -s $SERIAL -t $HOST 2>&1

echo 0 > $HOME/code
