#!/usr/bin/env bash
#
#   firmware - an fff script to update the FLM firmware after a bootloader interrupt
#
#   Copyright (C) 2015 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# exit codes
# 0: ok
# 126: not used
# 127: ffw did not finish its operation

# build the response header first
echo "HTTP/1.1 200 OK"
echo "Content-Type: text/plain"
echo "Transfer-Encoding: chunked"
echo ""

# ... followed by the response body
HOME=$PWD/cgi-bin
TOOLS=$HOME/tools

NOBUF="stdbuf -i0 -o0 -e0"

HOST="192.168.255.1"
KERNEL=firmware/openwrt-atheros-vmlinux.lzma
ROOTFS=firmware/openwrt-atheros-root.squashfs

echo 127 > $HOME/code

env PWDS=$TOOLS $NOBUF $TOOLS/ffw $HOST $KERNEL $ROOTFS 2>&1

echo $? > $HOME/code
