#!/usr/bin/env bash
#
#   status - an fff script returning the last command's status code
#
#   Copyright (C) 2012 Bart Van Der Meerssche <bart.vandermeerssche@flukso.net>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# build the response header first
echo "HTTP/1.1 200 OK"
echo "Content-Type: text/plain"
echo "Transfer-Encoding: chunked"
echo ""

# ... followed by the response body
HOME=$PWD/cgi-bin
NOBUF="$HOME/stdbuf -i0 -o0 -e0"

$NOBUF cat $HOME/code
