#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=40
STOP=40

boot() {
	setup_switch() { return 0; }

	include /lib/network
	setup_switch
	[ -s /etc/config/wireless ] || \
	/sbin/wifi detect > /etc/config/wireless
	/sbin/wifi up
	iwconfig ath0 rate 6M
}

start() {
	ifup -a
	/sbin/wifi up
	iwconfig ath0 rate 6M
}

restart() {
	setup_switch() { return 0; }

	include /lib/network
	setup_switch
	ifup -a
	/sbin/wifi up
	iwconfig ath0 rate 6M
}

stop() {
	ifdown -a
}

