#!/bin/sh
# Copyright (c) 2013 flukso.net

to_wifi ()
{
	uci set firewall.@zone[1].input=REJECT
	uci set network.wan.ifname=wlan0
	uci set network.lan.ifname=eth0
	uci set wireless.radio0.disabled=0
	uci set wireless.@wifi-iface[0].network=wan
	uci set wireless.@wifi-iface[0].mode=sta
	uci commit
	logger 'toggled to wifi mode'
}

to_eth ()
{
	uci set firewall.@zone[1].input=ACCEPT
	uci set network.wan.ifname=eth0
	uci set network.lan.ifname=wlan0
	uci set wireless.radio0.disabled=1
	uci set wireless.@wifi-iface[0].network=lan
	uci set wireless.@wifi-iface[0].mode=ap
	uci commit
	logger 'toggled to eth mode'
}

echo default-on > /sys/class/leds/globe/trigger

MODE=$(uci get network.wan.ifname)

if [ $MODE == eth0 ]
then
	to_wifi
elif [ $MODE == wlan0 ]
then
	to_eth
fi

/etc/init.d/network reload
sleep 10
/usr/bin/heartbeat 0
