#!/bin/sh
# Copyright (c) 2013 flukso.net

MAC=$(uci get wireless.radio0.macaddr)

cd /rom/etc/config
cp firewall network wireless /etc/config

logger 'returning to firewall, network and wireless defaults'

for i in 1 2 3 4 5
do
	echo default-on > /sys/class/leds/globe/trigger
	sleep 1
	echo none > /sys/class/leds/globe/trigger
	sleep 1
done

uci set wireless.radio0.macaddr=$MAC
uci commit

/etc/init.d/network reload
sleep 10
/usr/bin/heartbeat 0
